FROM node:18
WORKDIR /app
COPY ./package.json /app
COPY ./package-lock.json /app
COPY ./projects/external-companies/* /app
COPY . /app
RUN npm install
RUN npm install -g @angular/cli
CMD ["ng", "serve", "external-companies", "--host", "0.0.0.0"]




