FROM node:18
WORKDIR /app
COPY ./package.json /app
COPY ./package-lock.json /app
COPY ./projects/core/* /app
COPY . /app
RUN npm install
RUN npm install -g @angular/cli
CMD ["ng", "serve", "core", "--host", "0.0.0.0"]




